# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbemkehZVZmbU9_r4_Glu0kxnsFXGHOa

# ***WE will be using pycaret for classification problems in this notebook***
"""

! pip install pycaret

from pycaret.classification import *
data=pd.read_csv('/content/data.csv',engine='python')

exp=setup(data,target='diagnosis')

compare_models()
'''
List of available models:


Estimator	                    Abbreviated String
Logistic Regression	              ‘lr’
K Nearest Neighbour	              ‘knn’
Naives Bayes	                    ‘nb’
Decision Tree	                    ‘dt’
SVM (Linear)	                    ‘svm’
SVM (RBF)	                        ‘rbfsvm’
Gaussian Process	                ‘gpc’
Multi Level Perceptron	          ‘mlp’
Ridge Classifier	                ‘ridge’
Random Forest	                    ‘rf’
Quadratic Disc. Analysis	        ‘qda’
AdaBoost	                        ‘ada’
Gradient Boosting Classifier	    ‘gbc’
Linear Disc. Analysis	            ‘lda’
Extra Trees Classifier	          ‘et’
Extreme Gradient Boosting	        ‘xgboost’
Light Gradient Boosting	          ‘lightgbm’
Cat Boost Classifier	            ‘catboost’

'''

model=create_model('et')

model_tune=tune_model(model)#this will give us a tuned model

evaluate_model(model_tune)

deploy_model(model = lr, model_name = 'lr-for-deployment', platform = 'aws', authentication = {'bucket' : 'S3-bucket-name'})